### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by VRohit1901** [SiddheshNan/Acer-A515-51G-Hackintosh#10]
I used Niresh Catalina vanilla build to boot mac os. The keyboard and trackpad work but rest of the things don't work by default when i set the touchpad to basic in bios.But when I replace the whole clover file with yours keyboard and touchpad aren't working in basic as well as advanced also.

**Comment by jeffrjbra** [comment]
Please tell us:
Model:
BIOS Version:
MacOS Build:

**Comment by VRohit1901** [comment]
> Please tell us:
> Model:
> BIOS Version:
> MacOS Build:

> Model: Acer Aspire 5 (A515-51) Non-gpu version
> BIOS Version: V2.02
> MacOS Build: 10.15

**Comment by SiddheshNan** [comment]
Set Trackpad to Advance Mode in order to work everything properly.
To fix keyboard check following guide: https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh/blob/master/Keyboard-Fix.md
