### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by arkaprovaz** [SiddheshNan/Acer-A515-51G-Hackintosh#12]
Hi,

I am trying to get Mac OSx Catalina up and running on my Acer A515-51G. Up till now all things seem to be working except the Wifi (I am going to get the Qualcom Atheros card get replaced by Broadcom one. **DW1560**) and the keyboard. I have tried to patch the VoodooPS2Controller.kext but no luck. However the touchpad is working fine along with multi-finger gesture support.
Is there any way to enable the keyboard anyway?

**Comment by SiddheshNan** [comment]
Hey, 
Right now keyboard only works with v1.19 BIOS, But I'm Working to get work with the latest BIOS.
Can you please try with the following guide: https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh/blob/master/Keyboard-Fix.md
Right now you can follow the guide, Once it's I fix it you can update the BIOS to latest version.

Best.

**Comment by SiddheshNan** [comment]
Marked as resolved.
