### ISSUE TITLE
Not 4k resolution

### ISSUE THREAD

**Issue by iverdugocl** [SiddheshNan/Acer-A515-51G-Hackintosh#13]
Hello. I can't get 4k on my tv using hdmi cable. I get 1080p as max resolution. 
How can i get 4k?

**Comment by SiddheshNan** [comment]
Hey, sorry for late reply. . .
Use boot arg -cdfon in clover to get higher resolutions than 1080p. It enables 'CoreDisplayFixup' related code/patching in WhateverGreen.kext. you can find more docs here:

https://github.com/acidanthera/WhateverGreen/blob/master/README.md

https://www.reddit.com/r/hackintosh/comments/9keinh/bizarre_incompatibility_with_whatevergreen_boot/
