### ISSUE TITLE
Audio randomly not working after boot

### ISSUE THREAD

**Issue by SpiGAndromeda** [SiddheshNan/Acer-A515-51G-Hackintosh#14]
Hi,

the speakers aren't recognized in 50% of the boots. The problem seems completely random and a reboot mostly solves the problem but its annoying anyways. Is this a known  problem?

Layout-Id is 3 and AppleALC is 1.4.4

best regards,
spigandromeda

**Comment by SiddheshNan** [comment]
Yes, I'm aware of this issue. There is certain bug in appleALC which crashes the audio controller. Right now just revert back to AppleALC version 1.4.1 to solve the issue.

Best.

**Comment by SpiGAndromeda** [comment]
Ahh thanks alot!

**Comment by fishdeity** [comment]
AppleALC version 1.4.6 solves it for me too; I was having issues where logging off Windows 10 and then logging onto MacOS Catalina disabled my MacOS sounds. I also had to run the command for ALCPlugFix . If anyone is struggling with ALCPlugFix, make sure MAC SIP is disabled by running this in terminal : `csrutil disable`. If it says /usr/bin is read only folder, type these in terminal too:
`sudo mount -uw /`
`killall Finder`
after those terminal commands, the ALCPlugFix should work

**Comment by SiddheshNan** [comment]
Hey, Thanks for the info @fishdeity , I'll update the repo with the same.

Best.
