### ISSUE TITLE
Keyboard is not working

### ISSUE THREAD

**Issue by fboulegue** [SiddheshNan/Acer-A515-51G-Hackintosh#16]
I did set everything as explained - everything works fine but my keyboard is not at all anyone had this issue or have a hint?

When booting in -v I see that the backlight of keyboard turn off after a few sec

**Comment by SpiGAndromeda** [comment]
Hi @fboulegue 

this is a known BIOS problem as stated here: [](https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh/blob/master/Keyboard-Fix.md). There is also a solution on this page (which is a Readme from this project).

best regards,
spigandromeda

**Comment by fboulegue** [comment]
@SpiGAndromeda ohm in wich Readme) I just did check and could not find it

**Comment by fboulegue** [comment]
ah i see more or less downgrade my bios? So Windows is needed first of all ;-)? @SpiGAndromeda thanks for directing me

**Comment by SpiGAndromeda** [comment]
@fboulegue sorry ... I missed setting the hyperlink correctly.

**Comment by fboulegue** [comment]
@SpiGAndromeda got it :-) just not sure what bios version I should download the acer page is like .....

**Comment by SpiGAndromeda** [comment]
@fboulegue "You need v1.19 BIOS version"
