### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by Cristiano1103** [SiddheshNan/Acer-A515-51G-Hackintosh#18]
Keyboard not working, i have installed macOs Mojave, But keyboard not working.

**Comment by fishdeity** [comment]
Make sure you're on BIOS v1.19.

Instructions here on how to do it:
https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh/blob/master/Keyboard-Fix.md

**Comment by Cristiano1103** [comment]
Fixed!! thanks!
