### ISSUE TITLE
Audio ALC255

### ISSUE THREAD

**Issue by Cristiano1103** [SiddheshNan/Acer-A515-51G-Hackintosh#19]
The audio have a lot of noise.. i used eapd fix but not worked.. help?

**Comment by fishdeity** [comment]
you could try updating AppleALC.kext from version 1.4.4 to 1.4.6 to see if that helps. If not, you could then try injecting AppleALC.kext with different layout ids. Layout 3, 11, 13, 15, 17, 18, 21, 27, 28, 30, 31, 99 are the ones that supposedly could work. Remember to restart laptop after trying each injection

**Comment by Cristiano1103** [comment]
I already fixed, thanks!
post: https://www.elitemacx86.com/threads/fix-audio-distortion-when-using-headphones-on-laptops.185/
