### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Warmachine28** [SiddheshNan/Acer-A515-51G-Hackintosh#4]
I made bootable macos usb drive and installed clover and copied your configs in clover folder through VM as I have no access to any Mac. It's stuck on this. Little help needed to boot into macos. If you can guide to correctly configure bootable usb for macos will be quite helpful, if I may be doing something wrong for some reason.
![IMG_20190711_112448](https://user-images.githubusercontent.com/14938678/61025765-456f7180-a3cf-11e9-8b4f-fcadd28c7cca.jpg)
![IMG_20190711_112410](https://user-images.githubusercontent.com/14938678/61025767-46080800-a3cf-11e9-8ca4-1763f83cb7d9.jpg)

**Comment by SiddheshNan** [comment]
Okay, can you answer some of my questions;
1. are you installing macOS on SSD?
2. did you copied contains of this repo to clover folder of EFI partition of boot USB?

**Comment by Warmachine28** [comment]
Not actually I'm just trying on hard drive if all works then will swap my Linux partition. Idc I copied all the contents of repo to clover folder. Actually I used branch without WiFi card kexts

**Comment by Warmachine28** [comment]
Btw I actually passed to go through installation but it getting kernel panics while getting to setting up Mac. Passed this one but after this it gets rebooted and never made it self to setting Mac cz of kernel panics
![15628568294213346325619969949397](https://user-images.githubusercontent.com/14938678/61061421-d9662b00-a419-11e9-8ece-e811999ecbc5.jpg)

**Comment by SiddheshNan** [comment]
can you try this config.plist? I have removed TRIM patch which is used for SSDs. replace config.plist with this one & generate the system definitions of macbook pro 15.2 from clover configurator. 
[config.plist.zip](https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh/files/3382631/config.plist.zip)

**Comment by Warmachine28** [comment]
Ok trying and reporting soon :)

**Comment by SiddheshNan** [comment]
Can you message here if you have any problems https://gitter.im/Acer-A515-51G-Hackintosh

**Comment by Warmachine28** [comment]
No luck kernel panic again

**Comment by Warmachine28** [comment]
Sure ok

**Comment by Warmachine28** [comment]
Would you check gitter please!

**Comment by SiddheshNan** [comment]
oh yeah, sorry.

**Comment by Warmachine28** [comment]
Would you mind checking gitter please?

**Comment by Warmachine28** [comment]
Would you mind checking gitter please!
