### ISSUE TITLE
Keyboard Does't work

### ISSUE THREAD

**Issue by Cristiano1103** [SiddheshNan/Acer-A515-51G-Hackintosh#6]
All Works ... But keyboard not.. :(

**Comment by SiddheshNan** [comment]
I'm on it, will update repo for catalina once it comes out.

**Comment by SiddheshNan** [comment]
@Cristiano1103 Can you check with current repo?

**Comment by rahulbablu** [comment]
Keyboard doesn't work on 10.15.1
