### ISSUE TITLE
Keyboard still didn't work

### ISSUE THREAD

**Issue by jeffrjbra** [SiddheshNan/Acer-A515-51G-Hackintosh#9]
New repo is perfect, everything works fine, but keyboard didn't work after the use of this repo...

Some tips to make it work?

**Comment by rahulbablu** [comment]
What's ur bios version?

**Comment by jeffrjbra** [comment]
Version:
2.02

**Comment by rahulbablu** [comment]
U need to downgrade your bios v1.19 to make keyboard work fine

**Comment by rahulbablu** [comment]
https://gitter.im/Acer-A515-51G-Hackintosh/community?source=orgpage

Join here for more help

**Comment by jeffrjbra** [comment]
Ok, ill start the procedure and update soon!! Thanks

**Comment by SiddheshNan** [comment]
@rahulbablu Thanks for the follow up, I'll add those instructions soon to the Repo.
Thanks!

**Comment by jeffrjbra** [comment]
worked, im in  1.19 version again, just did!

**Comment by jeffrjbra** [comment]
now lets try to run Hackintosh again with working keyboard...lets see

**Comment by jeffrjbra** [comment]
WOW, worked!!
keyboard is working fine with the REPO!
screen is fixed too, no more scrambled colors!
thanks to everyone who made it!

**Comment by SiddheshNan** [comment]
Good, Marking solved.
